version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "PATCH: "
      prefix-development: "dev update: "
    labels:
      - "dependencies"
    versioning-strategy: increase
